# Base image
FROM node:10.15.3 AS builder

# Create and set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY package*.json ./
RUN npm install

COPY . ./

#Build project
RUN npm run build

##########################

FROM nginx:latest
EXPOSE 80
COPY --from=builder /usr/src/app/build /usr/share/nginx/html/
CMD ["nginx", "-g", "daemon off;"]